import express from "express";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import * as snarkjs from "snarkjs";
import { PROJECT_ROOT, findPolicy, loadPolicy } from "./config.ts";
import { claimRedemption } from "./db.ts";
import type { ProofPayload } from "../shared/types.ts";

const app = express();
app.use(express.json({ limit: "256kb" }));

// The verification key is generated by the demo Groth16 setup.
const verificationKey = JSON.parse(
  readFileSync(join(PROJECT_ROOT, "server-config/verification_key.json"), "utf8"),
);

// Order of public signals is fixed by the circuit:
// [root, threshold, activityId, nullifier]
const IDX_ROOT = 0;
const IDX_THRESHOLD = 1;
const IDX_ACTIVITY = 2;
const IDX_NULLIFIER = 3;

app.get("/api/health", (_req, res) => {
  res.json({ status: "ok" });
});

// Public policy: trusted root + configured activities and thresholds.
app.get("/api/policy", (_req, res) => {
  const policy = loadPolicy();
  res.json({
    root: policy.root,
    depth: policy.depth,
    activities: policy.activities.map((a) => ({
      id: a.id,
      activityId: a.activityId,
      name: a.name,
      threshold: a.threshold,
    })),
  });
});

app.post("/api/redeem", async (req, res) => {
  const payload = req.body as Partial<ProofPayload>;
  // Never log the body: although it only contains public outputs + proof,
  // the service is designed to avoid recording holder-derived data beyond
  // the atomic (activity, nullifier) record.

  if (
    !payload ||
    typeof payload.activityId !== "string" ||
    !Array.isArray(payload.publicSignals) ||
    payload.publicSignals.length !== 4 ||
    !payload.proof ||
    typeof payload.proof !== "object"
  ) {
    res.status(400).json({ ok: false, error: "invalid payload" });
    return;
  }

  const policy = findPolicy(payload.activityId);
  if (!policy) {
    res.status(400).json({ ok: false, error: "unknown activity" });
    return;
  }

  const signals = payload.publicSignals as string[];
  if (!signals.every((s) => typeof s === "string" && /^\d+$/.test(s))) {
    res.status(400).json({ ok: false, error: "invalid public signals" });
    return;
  }

  // Server-side policy enforcement: the client cannot choose a root,
  // lower the threshold or bind to a different activity.
  if (BigInt(signals[IDX_ROOT]) !== BigInt(loadPolicy().root)) {
    res.status(400).json({ ok: false, error: "root does not match trusted root" });
    return;
  }
  if (BigInt(signals[IDX_THRESHOLD]) !== BigInt(policy.threshold)) {
    res.status(400).json({ ok: false, error: "threshold does not match configured policy" });
    return;
  }
  if (BigInt(signals[IDX_ACTIVITY]) !== BigInt(policy.activityId)) {
    res.status(400).json({ ok: false, error: "activity mismatch" });
    return;
  }

  let valid: boolean;
  try {
    valid = await snarkjs.groth16.verify(verificationKey, signals, payload.proof);
  } catch {
    res.status(400).json({ ok: false, error: "proof malformed" });
    return;
  }
  if (!valid) {
    res.status(400).json({ ok: false, error: "invalid proof" });
    return;
  }

  // Proof is valid; claim atomically. Failed duplicates do not change state
  // (the earlier successful claim remains the only record).
  const claimed = claimRedemption(policy.activityId, signals[IDX_NULLIFIER]);
  if (!claimed) {
    res.status(409).json({ ok: false, error: "already redeemed for this activity", duplicate: true });
    return;
  }

  res.json({
    ok: true,
    activity: policy.id,
    name: policy.name,
    nullifier: signals[IDX_NULLIFIER],
  });
});

export function startServer(port = Number(process.env.PORT || 3101)) {
  const server = app.listen(port, "127.0.0.1", () => {
    const address = server.address();
    const actual = typeof address === "object" && address ? address.port : port;
    console.log(`verification server listening on http://127.0.0.1:${actual}`);
  });
  return server;
}

export { app };

const entry = process.argv[1] ?? "";
const isMain = /server[/\\]index\.(ts|js|mjs|cjs)$/.test(entry) ||
  /tsx$/.test(entry) && process.argv.includes("server/index.ts");
if (isMain) startServer();
